// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eInvoice.infra.efc.Data;

#nullable disable

namespace eInvoice.infra.efc.Migrations
{
    [DbContext(typeof(BillingContext))]
    [Migration("20251029130642_InvoiceDetailsAltered")]
    partial class InvoiceDetailsAltered
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.BankData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Ibanid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Swiftid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("BankData", (string)null);
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.BusinessProcessProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("BusinessProcessProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 256, DateTimeKind.Unspecified).AddTicks(7379), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "izdavanje računa za isporuke robe i usluga prema narudžbenicama, na temelju ugovora",
                            Name = "P1",
                            Updated = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 256, DateTimeKind.Unspecified).AddTicks(7379), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "periodično izdavanje računa za isporuke robe i usluga na temelju ugovora",
                            Name = "P2",
                            Updated = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 256, DateTimeKind.Unspecified).AddTicks(7379), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "izdavanje računa za isporuku prema samostalnoj narudžbenici",
                            Name = "P3",
                            Updated = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 256, DateTimeKind.Unspecified).AddTicks(7379), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "plaćanje unaprijed (avansno plaćanje)",
                            Name = "P4",
                            Updated = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 256, DateTimeKind.Unspecified).AddTicks(7379), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "plaćanje na licu mjesta (engl. Sport payment)",
                            Name = "P5",
                            Updated = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 256, DateTimeKind.Unspecified).AddTicks(7379), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "plaćanje prije isporuke, na temelju narudžbenice",
                            Name = "P6",
                            Updated = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 256, DateTimeKind.Unspecified).AddTicks(7379), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "izdavanje računa s referencama na otpremnicu",
                            Name = "P7",
                            Updated = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 256, DateTimeKind.Unspecified).AddTicks(7379), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "izdavanje računa s referencama na otpremnicu i primku",
                            Name = "P8",
                            Updated = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 256, DateTimeKind.Unspecified).AddTicks(7379), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "odobrenja ili računi s negativnim iznosima, izdani zbog raznih razloga, uključujući i povrat prazne ambalaže",
                            Name = "P9",
                            Updated = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 256, DateTimeKind.Unspecified).AddTicks(7379), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "izdavanje korektivnog računa (storniranje/ispravak računa)",
                            Name = "P10",
                            Updated = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 256, DateTimeKind.Unspecified).AddTicks(7379), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "izdavanje djelomičnoga i konačnog računa",
                            Name = "P11",
                            Updated = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 256, DateTimeKind.Unspecified).AddTicks(7379), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "samoizdavanje računa",
                            Name = "P12",
                            Updated = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 256, DateTimeKind.Unspecified).AddTicks(7379), new TimeSpan(0, 1, 0, 0, 0)),
                            Description = "poslovni proces koji definira Kupac",
                            Name = "P99",
                            Updated = new DateTimeOffset(new DateTime(2025, 10, 6, 11, 10, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.BusinessSpaceArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessSpaceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessSpaceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusinessSpaceArea");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.CommodityClassification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassificationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tariff")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Event", "Tariff");

                    b.HasIndex("Tariff", "Event");

                    b.ToTable("CommodityClassifications");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.CustomerMaster", b =>
                {
                    b.Property<string>("BankAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankCountryKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillToParty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityCountryKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Consignee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditControlArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerAccountGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomersCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistributionChannel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DunningBlock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DunningLevel")
                        .HasColumnType("int");

                    b.Property<string>("DunningProcedure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseBank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("IndividualLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IndustryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndustryKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterestIndicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockBox")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NatPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentBlock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReconciliationAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOffice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrganization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchTerm1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchTerm2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipToParty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoldToParty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TermsOfPaymentKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VatregNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WithholdingTaxCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WithholdingTaxIndicator")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("CustomerMaster", (string)null);
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.EdiinvoicingTo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("AltAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AltMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AltPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AltUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillToParty")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BuildingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastChecking")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSending")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoldToParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StpName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EdiinvoicingTo");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Approved")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BaselineDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BillOfLading")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillToParty")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("BillingDate")
                        .HasColumnType("datetime2");

                    b.Property<short?>("BillingMethod")
                        .HasColumnType("smallint")
                        .HasColumnName("billing_method");

                    b.Property<string>("CancelledBillingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Consignee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Controlled")
                        .HasColumnType("datetime2");

                    b.Property<string>("ControlledUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerRefNbr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DatePeriodFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePeriodTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtractStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Extracted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fiscalization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InvoiceStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Invoiced")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoicedUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ponumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Ratio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Rejected")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SapbillingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipToParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoldToParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TermsOfPaymentKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VesseVisitlId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VesselName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BillToParty");

                    b.HasIndex("InvoiceType");

                    b.HasIndex("InvoicedUser");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.InvoiceAdded", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DownloadTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<byte[]>("InvoiceMessage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastChange")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("SendingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SendingTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Sent")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("SnapshotAtt")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SnapshotPdf")
                        .HasColumnType("varbinary(max)");

                    b.Property<short?>("StatusId")
                        .HasColumnType("smallint");

                    b.Property<int?>("VatClauseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("InvoiceAdded");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.InvoiceAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("AttachmentXls")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("MimeCode")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber");

                    b.ToTable("InvoiceAttachments");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.InvoiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessProcessProfileId")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("SendingStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("Created")
                     .ValueGeneratedOnAdd()
                     .HasColumnType("datetimeoffset")
                     .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<DateTimeOffset?>("Updated")
                     .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BusinessProcessProfileId");

                    b.HasIndex("InvoiceNumber");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.InvoiceEvent", b =>
                {
                    b.Property<long>("Gkey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Gkey"));

                    b.Property<string>("Cat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Container")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescryptionHr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Event")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Imo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Invoice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Invoiced")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Item")
                        .HasColumnType("int");

                    b.Property<string>("LineOperatorId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("line_operator_id");

                    b.Property<string>("Measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayeeCustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Rf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Table")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tariff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Teu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VeselVisitId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VesselId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vessel_id");

                    b.Property<string>("VesselName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Gkey");

                    b.ToTable("InvoiceEvents", (string)null);
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltInvoiceNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("BasicPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BilledQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BilledQty1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BilledQtySku")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CancelledAltNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Event")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("Item")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("OutputTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PayBasicPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PayCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PayPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PayRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PayTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PayTaxClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PricingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Ratio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SalesUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesUnit1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tariff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaxClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ValidDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AltInvoiceNumber");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.InvoicePool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short?>("Containers20")
                        .HasColumnType("smallint");

                    b.Property<short?>("Containers40")
                        .HasColumnType("smallint");

                    b.Property<short?>("Containers45")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Idpool")
                        .HasColumnType("int");

                    b.Property<string>("Invoice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Invoiced")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Item")
                        .HasColumnType("int");

                    b.Property<string>("LineOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayeeCustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("PoolTeus")
                        .HasColumnType("smallint");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Select")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("Storage")
                        .HasColumnType("smallint");

                    b.Property<string>("Tariff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("TotalTeus")
                        .HasColumnType("smallint");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InvoicePools");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.InvoiceStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Carr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Container")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<short?>("Days")
                        .HasColumnType("smallint");

                    b.Property<short?>("Days1")
                        .HasColumnType("smallint");

                    b.Property<short?>("Days2")
                        .HasColumnType("smallint");

                    b.Property<short?>("Days3")
                        .HasColumnType("smallint");

                    b.Property<short?>("Days4")
                        .HasColumnType("smallint");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionHr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Eesgenerated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Event")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Free")
                        .HasColumnType("int");

                    b.Property<long>("Gkey")
                        .HasColumnType("bigint");

                    b.Property<string>("Imo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Invoice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Invoiced")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Item")
                        .HasColumnType("int");

                    b.Property<DateTime?>("JobTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LineOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OnTerminal")
                        .HasColumnType("int");

                    b.Property<string>("Oog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayeeCustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StorageTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Table")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tariff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TariffDays1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TariffDays2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TariffDays3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TariffDays4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Teu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotDays1")
                        .HasColumnType("int");

                    b.Property<int>("TotDays2")
                        .HasColumnType("int");

                    b.Property<int>("TotDays3")
                        .HasColumnType("int");

                    b.Property<int>("TotDays4")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VeselVisitId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VesselId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VesselName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InvoiceStorages");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.InvoiceTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceDescriptionLocal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SapbillingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VatClause")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VatClause");

                    b.ToTable("InvoiceType");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.SapInvoice", b =>
                {
                    b.Property<string>("AltInvoiceNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Changed")
                        .HasColumnType("datetime2");

                    b.Property<string>("DistrChanel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtractStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Extracted")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sapinvoice1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SAPinvoice");

                    b.HasKey("AltInvoiceNumber")
                        .HasName("PK_SepInvoice");

                    b.HasIndex("InvoiceNumber");

                    b.ToTable("SapInvoices", (string)null);
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.Tariff", b =>
                {
                    b.Property<string>("Tariff1")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Tariff");

                    b.Property<string>("Event")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short?>("BillingMethod")
                        .HasColumnType("smallint")
                        .HasColumnName("billing_method");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("datetime2");

                    b.Property<string>("EesSurcharge")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EES_surcharge");

                    b.Property<string>("EventGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupDays")
                        .HasColumnType("int");

                    b.Property<string>("Hazardous")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ImoEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsExport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsImport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsStorage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsTranship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OogEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oversize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SapdistChannel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sapdivision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surcharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Teu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Truck")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Units")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("VissibleInWh")
                        .HasColumnType("bit");

                    b.HasKey("Tariff1", "Event")
                        .HasName("PK_Tariffs1");

                    b.ToTable("tariffs", (string)null);
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.TariffDesc", b =>
                {
                    b.Property<string>("Tariff")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Event")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Tariff", "Event", "Language")
                        .HasName("PK_TariffDesc");

                    b.ToTable("TariffDesc", (string)null);
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("UserActiv")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UserChanged")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserChanger")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UserCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserCreator")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("UserChanger");

                    b.HasIndex("UserCreator");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.Vatclause", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceTextAlt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceTextLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Vatclause");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.VslVoyLine", b =>
                {
                    b.Property<string>("LineInVoyNbr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LineOpGkey")
                        .HasColumnType("bigint");

                    b.Property<string>("LineOpId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineOutVoyNbr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VesselId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("VslVoyLines", (string)null);
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.VslVoyage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Ata")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Atd")
                        .HasColumnType("datetime2");

                    b.Property<long>("CarrierGkey")
                        .HasColumnType("bigint");

                    b.Property<string>("CarrierMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CpxGkey")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CvcvdGkey")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndWork")
                        .HasColumnType("datetime2");

                    b.Property<long?>("FcyGkey")
                        .HasColumnType("bigint");

                    b.Property<long>("Gkey")
                        .HasColumnType("bigint");

                    b.Property<string>("IbVyg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("NextFcyGkey")
                        .HasColumnType("bigint");

                    b.Property<string>("ObVyg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OperatorGkey")
                        .HasColumnType("bigint");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadioCallSign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartWork")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TimeOffManifest")
                        .HasColumnType("datetime2");

                    b.Property<string>("VesselId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("VisitNbr")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("VslVoyages");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Models.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Configuration", (string)null);
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.BankData", b =>
                {
                    b.HasOne("eInvoice.infra.efc.Models.Company", "CompanyCodeNavigation")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyCodeNavigation");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.CommodityClassification", b =>
                {
                    b.HasOne("eInvoice.infra.efc.Infra.Models.Tariff", "TariffNavigation")
                        .WithMany()
                        .HasForeignKey("Tariff", "Event")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TariffNavigation");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.Invoice", b =>
                {
                    b.HasOne("eInvoice.infra.efc.Infra.Models.EdiinvoicingTo", "EdiinvoicingTo")
                        .WithMany()
                        .HasForeignKey("BillToParty")
                        .HasPrincipalKey("BillToParty");

                    b.HasOne("eInvoice.infra.efc.Infra.Models.InvoiceTypeEntity", null)
                        .WithMany("Invoices")
                        .HasForeignKey("InvoiceNumber")
                        .HasPrincipalKey("InvoiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eInvoice.infra.efc.Infra.Models.InvoiceTypeEntity", "InvoiceTypeNavigation")
                        .WithMany()
                        .HasForeignKey("InvoiceType")
                        .HasPrincipalKey("InvoiceTypeId");

                    b.HasOne("eInvoice.infra.efc.Infra.Models.User", "InvoicedUserNavigation")
                        .WithMany()
                        .HasForeignKey("InvoicedUser");

                    b.Navigation("EdiinvoicingTo");

                    b.Navigation("InvoiceTypeNavigation");

                    b.Navigation("InvoicedUserNavigation");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.InvoiceAttachment", b =>
                {
                    b.HasOne("eInvoice.infra.efc.Infra.Models.Invoice", "Invoice")
                        .WithMany("InvoiceAttachments")
                        .HasForeignKey("InvoiceNumber")
                        .HasPrincipalKey("InvoiceNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.InvoiceDetail", b =>
                {
                    b.HasOne("eInvoice.infra.efc.Infra.Models.BusinessProcessProfile", "BusinessProcessProfileNavigation")
                        .WithMany()
                        .HasForeignKey("BusinessProcessProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eInvoice.infra.efc.Infra.Models.Invoice", "InvoiceNavigation")
                        .WithMany()
                        .HasForeignKey("InvoiceNumber")
                        .HasPrincipalKey("InvoiceNumber");

                    b.Navigation("BusinessProcessProfileNavigation");

                    b.Navigation("InvoiceNavigation");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.InvoiceItem", b =>
                {
                    b.HasOne("eInvoice.infra.efc.Infra.Models.SapInvoice", "SapInvoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("AltInvoiceNumber");

                    b.Navigation("SapInvoice");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.InvoiceTypeEntity", b =>
                {
                    b.HasOne("eInvoice.infra.efc.Infra.Models.Vatclause", "VatClauseNavigation")
                        .WithMany()
                        .HasForeignKey("VatClause");

                    b.Navigation("VatClauseNavigation");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.SapInvoice", b =>
                {
                    b.HasOne("eInvoice.infra.efc.Infra.Models.Invoice", "Invoice")
                        .WithMany("SapInvoices")
                        .HasForeignKey("InvoiceNumber")
                        .HasPrincipalKey("InvoiceNumber");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.TariffDesc", b =>
                {
                    b.HasOne("eInvoice.infra.efc.Infra.Models.Tariff", "TariffNavigation")
                        .WithMany()
                        .HasForeignKey("Tariff", "Event")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TariffNavigation");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.User", b =>
                {
                    b.HasOne("eInvoice.infra.efc.Infra.Models.User", "UserChangerNavigation")
                        .WithMany()
                        .HasForeignKey("UserChanger");

                    b.HasOne("eInvoice.infra.efc.Infra.Models.User", "UserCreatorNavigation")
                        .WithMany()
                        .HasForeignKey("UserCreator");

                    b.Navigation("UserChangerNavigation");

                    b.Navigation("UserCreatorNavigation");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceAttachments");

                    b.Navigation("SapInvoices");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.InvoiceTypeEntity", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("eInvoice.infra.efc.Infra.Models.SapInvoice", b =>
                {
                    b.Navigation("InvoiceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
