//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// xscgen .\maindoc\UBL-Invoice-2.1.xsd
namespace Mfin.Gov.Hr.Schema.Xsd.HrExtensionAggregateComponents._1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("HRFISK20DataType", Namespace="urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("HRFISK20Data", Namespace="urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1")]
    public partial class Hrfisk20DataType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("HRObracunPDVPoNaplati")]
        public HrObracunPdvPoNaplatiType HrObracunPdvPoNaplati { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("HRTaxTotal")]
        public HrTaxTotalType HrTaxTotal { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("HRLegalMonetaryTotal")]
        public HrMonetaryTotalType HrLegalMonetaryTotal { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("HRObracunPDVPoNaplatiType", Namespace="urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HrObracunPdvPoNaplatiType : Oasis.Names.Specification.Ubl.Schema.Xsd.UnqualifiedDataTypes._2.TextType
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("HRTaxTotalType", Namespace="urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HrTaxTotalType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("TaxAmount", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.TaxAmountType TaxAmount { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<HrTaxSubtotalType> _hrTaxSubtotal;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("HRTaxSubtotal")]
        public System.Collections.ObjectModel.Collection<HrTaxSubtotalType> HrTaxSubtotal
        {
            get
            {
                return _hrTaxSubtotal;
            }
            private set
            {
                _hrTaxSubtotal = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HrTaxTotalType" /> class.</para>
        /// </summary>
        public HrTaxTotalType()
        {
            this._hrTaxSubtotal = new System.Collections.ObjectModel.Collection<HrTaxSubtotalType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("HRTaxSubtotalType", Namespace="urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HrTaxSubtotalType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("TaxableAmount", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.TaxableAmountType TaxableAmount { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("TaxAmount", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.TaxAmountType TaxAmount { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("HRTaxCategory")]
        public HrTaxCategoryType HrTaxCategory { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("HRTaxCategoryType", Namespace="urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HrTaxCategoryType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ID", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.IdType Id { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Name", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.NameType Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Percent", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.PercentType Percent { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TaxExemptionReasonCode", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.TaxExemptionReasonCodeType TaxExemptionReasonCode { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.TaxExemptionReasonType> _taxExemptionReason;
        
        [System.Xml.Serialization.XmlElementAttribute("TaxExemptionReason", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public System.Collections.ObjectModel.Collection<Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.TaxExemptionReasonType> TaxExemptionReason
        {
            get
            {
                return _taxExemptionReason;
            }
            private set
            {
                _taxExemptionReason = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the TaxExemptionReason collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxExemptionReasonSpecified
        {
            get
            {
                return (this.TaxExemptionReason.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="HrTaxCategoryType" /> class.</para>
        /// </summary>
        public HrTaxCategoryType()
        {
            this._taxExemptionReason = new System.Collections.ObjectModel.Collection<Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.TaxExemptionReasonType>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("HRTaxScheme")]
        public HrTaxSchemeType HrTaxScheme { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("HRTaxSchemeType", Namespace="urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HrTaxSchemeType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ID", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.IdType Id { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("HRMonetaryTotalType", Namespace="urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HrMonetaryTotalType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("TaxExclusiveAmount", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.TaxExclusiveAmountType TaxExclusiveAmount { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("OutOfScopeOfVATAmount")]
        public OutOfScopeOfVatAmountType OutOfScopeOfVatAmount { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("OutOfScopeOfVATAmountType", Namespace="urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OutOfScopeOfVatAmountType : Oasis.Names.Specification.Ubl.Schema.Xsd.UnqualifiedDataTypes._2.AmountType
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AccountingCurrencyPayableAmountType", Namespace="urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountingCurrencyPayableAmountType : Oasis.Names.Specification.Ubl.Schema.Xsd.UnqualifiedDataTypes._2.AmountType
    {
    }
}
