//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// xscgen .\maindoc\UBL-Invoice-2.1.xsd
namespace Oasis.Names.Specification.Ubl.Schema.Xsd.CommonExtensionComponents._2
{
    
    
    /// <summary>
    /// <para>A container for all extensions present in the document.</para>
    /// <para>A container for all extensions present in the document.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("A container for all extensions present in the document. A container for all exten" +
        "sions present in the document."))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("UBLExtensionsType", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("UBLExtensions", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    public partial class UblExtensionsType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<UblExtensionType> _ublExtension;
        
        /// <summary>
        /// <para>A single extension for private use.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A single extension for private use.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("UBLExtension")]
        public System.Collections.ObjectModel.Collection<UblExtensionType> UblExtension
        {
            get
            {
                return _ublExtension;
            }
            private set
            {
                _ublExtension = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="UblExtensionsType" /> class.</para>
        /// </summary>
        public UblExtensionsType()
        {
            this._ublExtension = new System.Collections.ObjectModel.Collection<UblExtensionType>();
        }
    }
    
    /// <summary>
    /// <para>A single extension for private use.</para>
    /// <para>A single extension for private use.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("A single extension for private use. A single extension for private use.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("UBLExtensionType", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("UBLExtension", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    public partial class UblExtensionType
    {
        
        /// <summary>
        /// <para>An identifier for the Extension assigned by the creator of the extension.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("An identifier for the Extension assigned by the creator of the extension.")]
        [System.Xml.Serialization.XmlElementAttribute("ID", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.IdType Id { get; set; }
        
        /// <summary>
        /// <para>A name for the Extension assigned by the creator of the extension.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A name for the Extension assigned by the creator of the extension.")]
        [System.Xml.Serialization.XmlElementAttribute("Name", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.NameType Name { get; set; }
        
        /// <summary>
        /// <para>An agency that maintains one or more Extensions.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("An agency that maintains one or more Extensions.")]
        [System.Xml.Serialization.XmlElementAttribute("ExtensionAgencyID")]
        public ExtensionAgencyIdType ExtensionAgencyId { get; set; }
        
        /// <summary>
        /// <para>The name of the agency that maintains the Extension.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The name of the agency that maintains the Extension.")]
        [System.Xml.Serialization.XmlElementAttribute("ExtensionAgencyName")]
        public ExtensionAgencyNameType ExtensionAgencyName { get; set; }
        
        /// <summary>
        /// <para>The version of the Extension.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The version of the Extension.")]
        [System.Xml.Serialization.XmlElementAttribute("ExtensionVersionID")]
        public ExtensionVersionIdType ExtensionVersionId { get; set; }
        
        /// <summary>
        /// <para>A URI for the Agency that maintains the Extension.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A URI for the Agency that maintains the Extension.")]
        [System.Xml.Serialization.XmlElementAttribute("ExtensionAgencyURI")]
        public ExtensionAgencyUriType ExtensionAgencyUri { get; set; }
        
        /// <summary>
        /// <para>A URI for the Extension.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A URI for the Extension.")]
        [System.Xml.Serialization.XmlElementAttribute("ExtensionURI")]
        public ExtensionUriType ExtensionUri { get; set; }
        
        /// <summary>
        /// <para>A code for reason the Extension is being included.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A code for reason the Extension is being included.")]
        [System.Xml.Serialization.XmlElementAttribute("ExtensionReasonCode")]
        public ExtensionReasonCodeType ExtensionReasonCode { get; set; }
        
        /// <summary>
        /// <para>A description of the reason for the Extension.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A description of the reason for the Extension.")]
        [System.Xml.Serialization.XmlElementAttribute("ExtensionReason")]
        public ExtensionReasonType ExtensionReason { get; set; }
        
        /// <summary>
        /// <para>The definition of the extension content.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The definition of the extension content.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ExtensionContent")]
        public ExtensionContentType ExtensionContent { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExtensionAgencyIDType", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ExtensionAgencyID", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    public partial class ExtensionAgencyIdType : Oasis.Names.Specification.Ubl.Schema.Xsd.UnqualifiedDataTypes._2.IdentifierType
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExtensionAgencyNameType", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ExtensionAgencyName", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    public partial class ExtensionAgencyNameType : Oasis.Names.Specification.Ubl.Schema.Xsd.UnqualifiedDataTypes._2.TextType
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExtensionVersionIDType", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ExtensionVersionID", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    public partial class ExtensionVersionIdType : Oasis.Names.Specification.Ubl.Schema.Xsd.UnqualifiedDataTypes._2.IdentifierType
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExtensionAgencyURIType", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ExtensionAgencyURI", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    public partial class ExtensionAgencyUriType : Oasis.Names.Specification.Ubl.Schema.Xsd.UnqualifiedDataTypes._2.IdentifierType
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExtensionURIType", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ExtensionURI", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    public partial class ExtensionUriType : Oasis.Names.Specification.Ubl.Schema.Xsd.UnqualifiedDataTypes._2.IdentifierType
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExtensionReasonCodeType", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ExtensionReasonCode", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    public partial class ExtensionReasonCodeType : Oasis.Names.Specification.Ubl.Schema.Xsd.UnqualifiedDataTypes._2.CodeType
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExtensionReasonType", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ExtensionReason", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    public partial class ExtensionReasonType : Oasis.Names.Specification.Ubl.Schema.Xsd.UnqualifiedDataTypes._2.TextType
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExtensionContentType", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ExtensionContent", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
    public partial class ExtensionContentType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("HRFISK20Data", Namespace="urn:mfin.gov.hr:schema:xsd:HRExtensionAggregateComponents-1")]
        public Mfin.Gov.Hr.Schema.Xsd.HrExtensionAggregateComponents._1.Hrfisk20DataType Hrfisk20Data { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Oasis.Names.Specification.Ubl.Schema.Xsd.SignatureAggregateComponents._2.SignatureInformationType> _ublDocumentSignatures;
        
        [System.Xml.Serialization.XmlArrayAttribute("UBLDocumentSignatures", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2")]
        [System.Xml.Serialization.XmlArrayItemAttribute("SignatureInformation", Namespace="urn:oasis:names:specification:ubl:schema:xsd:SignatureAggregateComponents-2")]
        public System.Collections.ObjectModel.Collection<Oasis.Names.Specification.Ubl.Schema.Xsd.SignatureAggregateComponents._2.SignatureInformationType> UblDocumentSignatures
        {
            get
            {
                return _ublDocumentSignatures;
            }
            private set
            {
                _ublDocumentSignatures = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the UblDocumentSignatures collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UblDocumentSignaturesSpecified
        {
            get
            {
                return (this.UblDocumentSignatures.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ExtensionContentType" /> class.</para>
        /// </summary>
        public ExtensionContentType()
        {
            this._ublDocumentSignatures = new System.Collections.ObjectModel.Collection<Oasis.Names.Specification.Ubl.Schema.Xsd.SignatureAggregateComponents._2.SignatureInformationType>();
        }
    }
}
