//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// xscgen .\maindoc\UBL-Invoice-2.1.xsd
namespace Oasis.Names.Specification.Ubl.Schema.Xsd.CommonSignatureComponents._2
{
    
    
    /// <summary>
    /// <para><ccts:Component xmlns:ccts="urn:un:unece:uncefact:documentation:2"><ccts:ComponentType>ABIE</ccts:ComponentType><ccts:DictionaryEntryName>UBL Document Signatures. Details</ccts:DictionaryEntryName><ccts:Definition>This class collects all signature information for a document.</ccts:Definition><ccts:ObjectClass>UBL Document Signatures</ccts:ObjectClass></ccts:Component></para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"<ccts:Component xmlns:ccts=""urn:un:unece:uncefact:documentation:2""><ccts:ComponentType>ABIE</ccts:ComponentType><ccts:DictionaryEntryName>UBL Document Signatures. Details</ccts:DictionaryEntryName><ccts:Definition>This class collects all signature information for a document.</ccts:Definition><ccts:ObjectClass>UBL Document Signatures</ccts:ObjectClass></ccts:Component>")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("UBLDocumentSignaturesType", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("UBLDocumentSignatures", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2")]
    public partial class UblDocumentSignaturesType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Oasis.Names.Specification.Ubl.Schema.Xsd.SignatureAggregateComponents._2.SignatureInformationType> _signatureInformation;
        
        /// <summary>
        /// <para><ccts:Component xmlns:ccts="urn:un:unece:uncefact:documentation:2"><ccts:ComponentType>ASBIE</ccts:ComponentType><ccts:DictionaryEntryName>UBL Document Signatures. Signature Information</ccts:DictionaryEntryName><ccts:Definition>Each of these is scaffolding for a single digital signature.</ccts:Definition><ccts:Cardinality>1..n</ccts:Cardinality><ccts:ObjectClass>UBL Document Signatures</ccts:ObjectClass><ccts:PropertyTerm>Signature Information</ccts:PropertyTerm><ccts:AssociatedObjectClass>Signature Information</ccts:AssociatedObjectClass><ccts:RepresentationTerm>Signature Information</ccts:RepresentationTerm></ccts:Component></para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"<ccts:Component xmlns:ccts=""urn:un:unece:uncefact:documentation:2""><ccts:ComponentType>ASBIE</ccts:ComponentType><ccts:DictionaryEntryName>UBL Document Signatures. Signature Information</ccts:DictionaryEntryName><ccts:Definition>Each of these is scaffolding for a single digital signature.</ccts:Definition><ccts:Cardinality>1..n</ccts:Cardinality><ccts:ObjectClass>UBL Document Signatures</ccts:ObjectClass><ccts:PropertyTerm>Signature Information</ccts:PropertyTerm><ccts:AssociatedObjectClass>Signature Information</ccts:AssociatedObjectClass><ccts:RepresentationTerm>Signature Information</ccts:RepresentationTerm></ccts:Component>")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("SignatureInformation", Namespace="urn:oasis:names:specification:ubl:schema:xsd:SignatureAggregateComponents-2")]
        public System.Collections.ObjectModel.Collection<Oasis.Names.Specification.Ubl.Schema.Xsd.SignatureAggregateComponents._2.SignatureInformationType> SignatureInformation
        {
            get
            {
                return _signatureInformation;
            }
            private set
            {
                _signatureInformation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="UblDocumentSignaturesType" /> class.</para>
        /// </summary>
        public UblDocumentSignaturesType()
        {
            this._signatureInformation = new System.Collections.ObjectModel.Collection<Oasis.Names.Specification.Ubl.Schema.Xsd.SignatureAggregateComponents._2.SignatureInformationType>();
        }
    }
}
