//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// xscgen .\maindoc\UBL-AttachedDocument-2.1.xsd
namespace Oasis.Names.Specification.Ubl.Schema.Xsd.AttachedDocument._2
{
    
    
    /// <summary>
    /// <para>A UBL  wrapper  that allows a document of any kind to be packaged with the UBL document that references it.</para>
    /// <para>This element MUST be conveyed as the root element in any instance document based on this Schema expression</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("A UBL wrapper that allows a document of any kind to be packaged with the UBL docu" +
        "ment that references it. This element MUST be conveyed as the root element in an" +
        "y instance document based on this Schema expression"))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AttachedDocumentType", Namespace="urn:oasis:names:specification:ubl:schema:xsd:AttachedDocument-2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("AttachedDocument", Namespace="urn:oasis:names:specification:ubl:schema:xsd:AttachedDocument-2")]
    public partial class AttachedDocumentType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Oasis.Names.Specification.Ubl.Schema.Xsd.CommonExtensionComponents._2.UblExtensionType> _ublExtensions;
        
        /// <summary>
        /// <para>A container for all extensions present in the document.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A container for all extensions present in the document.")]
        [System.Xml.Serialization.XmlArrayAttribute("UBLExtensions", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
        [System.Xml.Serialization.XmlArrayItemAttribute("UBLExtension", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
        public System.Collections.ObjectModel.Collection<Oasis.Names.Specification.Ubl.Schema.Xsd.CommonExtensionComponents._2.UblExtensionType> UblExtensions
        {
            get
            {
                return _ublExtensions;
            }
            private set
            {
                _ublExtensions = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the UblExtensions collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UblExtensionsSpecified
        {
            get
            {
                return (this.UblExtensions.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="AttachedDocumentType" /> class.</para>
        /// </summary>
        public AttachedDocumentType()
        {
            this._ublExtensions = new System.Collections.ObjectModel.Collection<Oasis.Names.Specification.Ubl.Schema.Xsd.CommonExtensionComponents._2.UblExtensionType>();
            this._note = new System.Collections.ObjectModel.Collection<Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.NoteType>();
            this._signature = new System.Collections.ObjectModel.Collection<Oasis.Names.Specification.Ubl.Schema.Xsd.CommonAggregateComponents._2.SignatureType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("UBLVersionID", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.UblVersionIdType UblVersionId { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("CustomizationID", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.CustomizationIdType CustomizationId { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ProfileID", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.ProfileIdType ProfileId { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ProfileExecutionID", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.ProfileExecutionIdType ProfileExecutionId { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ID", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.IdType Id { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("UUID", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.UuidType Uuid { get; set; }
        
        /// <summary>
        /// <para>A date denoting when the Attached Document was issued.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A date denoting when the Attached Document was issued.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("IssueDate", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.IssueDateType IssueDate { get; set; }
        
        /// <summary>
        /// <para>A time denoting when the Attached Document was issued.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A time denoting when the Attached Document was issued.")]
        [System.Xml.Serialization.XmlElementAttribute("IssueTime", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.IssueTimeType IssueTime { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.NoteType> _note;
        
        /// <summary>
        /// <para>Contains any free-form text pertinent to the entire document or to the document message itself. This element may contain notes or any other similar information that is not contained explicitly in another structure.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Contains any free-form text pertinent to the entire document or to the document m" +
            "essage itself. This element may contain notes or any other similar information t" +
            "hat is not contained explicitly in another structure."))]
        [System.Xml.Serialization.XmlElementAttribute("Note", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public System.Collections.ObjectModel.Collection<Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.NoteType> Note
        {
            get
            {
                return _note;
            }
            private set
            {
                _note = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Note collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoteSpecified
        {
            get
            {
                return (this.Note.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>Qualifies the type of document using a code set.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Qualifies the type of document using a code set.")]
        [System.Xml.Serialization.XmlElementAttribute("DocumentTypeCode", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.DocumentTypeCodeType DocumentTypeCode { get; set; }
        
        /// <summary>
        /// <para>Qualifies types of document as text.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Qualifies types of document as text.")]
        [System.Xml.Serialization.XmlElementAttribute("DocumentType", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.DocumentTypeType DocumentType { get; set; }
        
        /// <summary>
        /// <para>Identifies the parent document.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identifies the parent document.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ParentDocumentID", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.ParentDocumentIdType ParentDocumentId { get; set; }
        
        /// <summary>
        /// <para>Identifies the type of parent document.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identifies the type of parent document.")]
        [System.Xml.Serialization.XmlElementAttribute("ParentDocumentTypeCode", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonBasicComponents._2.ParentDocumentTypeCodeType ParentDocumentTypeCode { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Oasis.Names.Specification.Ubl.Schema.Xsd.CommonAggregateComponents._2.SignatureType> _signature;
        
        /// <summary>
        /// <para>Associates the Attached Document with zero or more signatures.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Associates the Attached Document with zero or more signatures.")]
        [System.Xml.Serialization.XmlElementAttribute("Signature", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public System.Collections.ObjectModel.Collection<Oasis.Names.Specification.Ubl.Schema.Xsd.CommonAggregateComponents._2.SignatureType> Signature
        {
            get
            {
                return _signature;
            }
            private set
            {
                _signature = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Signature collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SignatureSpecified
        {
            get
            {
                return (this.Signature.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>An association to the Party sending this document.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("An association to the Party sending this document.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("SenderParty", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonAggregateComponents._2.PartyType SenderParty { get; set; }
        
        /// <summary>
        /// <para>An association to the Party receiving this document.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("An association to the Party receiving this document.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ReceiverParty", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonAggregateComponents._2.PartyType ReceiverParty { get; set; }
        
        /// <summary>
        /// <para>An attachment containing the document content.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("An attachment containing the document content.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Attachment", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public Oasis.Names.Specification.Ubl.Schema.Xsd.CommonAggregateComponents._2.AttachmentType Attachment { get; set; }
    }
}
